name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.13'
      - run: npm install -g grunt-cli
      - run: npm install
      - run: git status

